CREATE TABLE cdst.ente_appoggio_csv
(
    cod_amm character varying(255) COLLATE pg_catalog."default",
    des_amm character varying(255) COLLATE pg_catalog."default",
    comune character varying(255) COLLATE pg_catalog."default",
    nome_resp character varying(255) COLLATE pg_catalog."default",
    cogn_resp character varying(255) COLLATE pg_catalog."default",
    cap character varying(255) COLLATE pg_catalog."default",
    provincia character varying(255) COLLATE pg_catalog."default",
    regione character varying(255) COLLATE pg_catalog."default",
    sito_istituzionale character varying(255) COLLATE pg_catalog."default",
    indirizzo character varying(255) COLLATE pg_catalog."default",
    titolo_resp character varying(255) COLLATE pg_catalog."default",
    tipologia_istat character varying(255) COLLATE pg_catalog."default",
    tipologia_amm character varying(255) COLLATE pg_catalog."default",
    acronimo character varying(255) COLLATE pg_catalog."default",
    cf_validato character varying(255) COLLATE pg_catalog."default",
    cf character varying(255) COLLATE pg_catalog."default",
    mail1 character varying(255) COLLATE pg_catalog."default",
    tipo_mail1 character varying(255) COLLATE pg_catalog."default",
    mail2 character varying(255) COLLATE pg_catalog."default",
    tipo_mail2 character varying(255) COLLATE pg_catalog."default",
    mail3 character varying(255) COLLATE pg_catalog."default",
    tipo_mail3 character varying(255) COLLATE pg_catalog."default",
    mail4 character varying(255) COLLATE pg_catalog."default",
    tipo_mail4 character varying(255) COLLATE pg_catalog."default",
    mail5 character varying(255) COLLATE pg_catalog."default",
    tipo_mail5 character varying(255) COLLATE pg_catalog."default",
    url_facebook character varying(600) COLLATE pg_catalog."default",
    url_twitter character varying(600) COLLATE pg_catalog."default",
    url_googleplus character varying(600) COLLATE pg_catalog."default",
    url_youtube character varying(600) COLLATE pg_catalog."default",
    liv_accessibili character varying(600) COLLATE pg_catalog."default"
)