INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (1,  1, 'endIntegrationDate', true,  5, 15, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (2,  1, 'endOpinionDate'    , true,  5, 45, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (3,  1, 'firstSessionDate'  , true,  0, 10, 'endOpinionDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (4,  1, 'expirationDate'    , true,  0, 45, 'firstSessionDate');
                                                                                                                                                                                                                                                                        
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (5,  2, 'endIntegrationDate', true,  5, 15, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (6,  2, 'endOpinionDate'    , false, 5, 45, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (7,  2, 'firstSessionDate'  , true,  5, 45, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (8,  2, 'expirationDate'    , true,  0, 45, 'firstSessionDate');
                                                                                                                                                                                                                                        
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (9,  3, 'endIntegrationDate', true,  2, 10, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (10, 3, 'endOpinionDate'    , false, 0, 0,  'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (11, 3, 'firstSessionDate'  , true,  0, 3,  'endIntegrationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (12, 3, 'expirationDate'    , true,  0, 15, 'firstSessionDate');

INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (13, 4, 'endIntegrationDate', true,  5, 15, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (14, 4, 'endOpinionDate'    , false, 5, 45, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (15, 4, 'firstSessionDate'  , true,  5, 45, 'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (16, 4, 'expirationDate'    , true,  0, 45, 'firstSessionDate');

INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (17, 5, 'endIntegrationDate', false, 0, 0,  'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (18, 5, 'endOpinionDate'    , false, 0, 0,  'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (19, 5, 'firstSessionDate'  , true,  0, 0,  'creationDate');
INSERT INTO cdst.tipologia_conferenza_data_definizione(id_tipologia_conferenza_date_definizione, fk_tipologia_conferenza, campo_data_calcolato, flag_obbligatorio, offset_gg_lavorativi, offset_gg_solari, campo_data_base)	VALUES (20, 5, 'expirationDate'    , true,  0, 0,  'firstSessionDate');