export enum ConferenceType {
    SIMPLIFY = '1',
    CONCURRENTLY = '2',
    REGIONAL = '3',
    BROADBAND = '4',
    PRELIMINARY = '5',
    DOMUS = '6',
    OPERATIONAL_MEETING = '7',
    ENVIRONMENT_INVESTIGATION_VIA = '8',
    ENVIRONMENT_DEFINITION_VIA = '9',
    ENVIRONMENT_INVESTIGATION_AIA = '10',
    ENVIRONMENT_DEFINITION_AIA = '11',
    INFORMATICS = '12',
}
