export enum DateType {
    DATA_TERMINE = 'DATA_TERMINE',
    DATA_PRIMA_SESSIONE_SIMULATA = 'DATA_PRIMA_SESSIONE_SIMULTANEA',
    DATA_TERMINE_ESPRESSIONE_PARERI = 'DATA_TERMINE_ESPRESSIONE_PARERI',
    DATA_TERMINE_RICHIESTA_INTEGRAZIONI_CONFERENZA = 'DATA_TERMINE_RICHIESTA_INTEGRAZIONI_CONFERENZA',
    DATA_PRIMA_SESSIONE_SIMULTANEA = 'DATA_PRIMA_SESSIONE_SIMULTANEA'
}
