export enum EventType {
    CONFERENCE_CREATED = '1',
    CONFERENCE_INDICTION = '2',
    INTEGRATION_REQUEST = '3',
    INTEGRATION_CLOSED = '4',
    INTEGRATION_ONLY_ONE_REQUEST = '5',
    INTEGRATION_SEND = '6',
    GENERIC_COMUNICATION = '7',
    CONFERENCE_LINK = '8',
    CONFERENCE_MEMO = '9',
    CONFERENCE_MEMO_INTERNAL = '31',
    CONFERENCE_CLOSING = '10',
    OPINION_EXPRESS = '11',
    FINAL_RESOLUTION = '12',
    INTEGRATION_REGISTERED = '13',
    EDIT_DATE = '26'
}
