export enum ParticipantRole {
    APPLICANT = '1',
    PROCEEDING_ADMINISTRATION = '2',
    COMPETENT_ADMINISTRATION = '3',
    INTERESTED_ADMINISTRATION = '4',
    INTERNAL_OPINIONS_ADMINISTRATION = '5',
    INFORMATION_ADMINISTRATION = '6'
}
