export * from './pec/main/pec.component';
export * from './definition/main/definition.component';
export * from './documentation';
export * from './participants';
export * from './events';
export * from './participants/components/participants-table/participants-table.component';
export * from './procedure/main/procedure.component';
export * from './summary/main/summary.component';
export * from './accreditation';
