package conferenza.consolleAmministrativa.repository.specification;

import conferenza.consolleAmministrativa.model.RicercaRubricaDelegati;
import conferenza.repository.SpecificationBuilder;

public class SpecificationBuilderRicercaRubricaDelegati extends SpecificationBuilder<RicercaRubricaDelegati>{

}
