export enum AppSections {
    CONFERENCE_INDICTION_FILE,
    CONFERENCE_SIGN_FILE,
    CONFERENCE_EVENTS_COMBO_BOX,
    CONFERENCE_ACCREDITATION,
    CONFERENCE_PEC,
    CONFERENCE_WIZARD,
    RESULT_TABLE,
    RESULT_TABLE_ACTIONS,
    CONFERENCE_DETAIL_ROUTE,
    CONFERENCE_STEP,
    CONFERENCE_ALERT_INFO,
    SIDE_MENU,
    CONFERENCE_PROTOCOL
}
