export enum FileType {    
    SIGNATURE = "DOCUMENTO_FIRMATO",
    ADDITIONAL = 'DOCUMENTAZIONE_AGGIUNTIVA',
    INTERETION = 'INTERAZIONI',
    INDICTION = 'DOCUMENTO_INDIZIONE',
    ACCREDITATION = 'DOCUMENTO_ACCREDITAMENTO',
    PRELIMINARY = 'DOCUMENTO_PRE_ISTRUTTORIA',
    CONFERENCE_MEMO = 'VERBALE_RIUNIONE',
    CONFERENCE_MEMO_INTERNAL = 'VERBALE_RIUNIONE_INTERNO',
    GENERIC_COMUNICATION = 'COMUNICAZIONE_GENERICA',
    FINAL_RESOLUTION = 'DETERMINA',
    OPINION_EXPRESS = 'ESPRESSIONE_PARERI',
    SHARED = 'DOCUMENTI_CONDIVISI',
}
