export enum SectionLoading {
    ALL_CONTENT,
    SEARCH,
    EVENTS_MODAL,
    ACCREDITATION_TAB,
    ACCREDITATION_MODAL,
    PEC_TAB,
    INDICTION_FILE_MODAL,
    PARTICIPANT_MODAL,
    CONFERENCE_MODAL_BEFORE_CREATE,
    CONFERENCE_FOOTER_BUTTON,
    SHARED_FILE_MODAL,
    SIGNATURE_FILE_MODAL,
    CLONE_MODAL,
    MODAL_SIGN  
}
